name: Deploy To Production

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Deploying everything to the Production server
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into Server And Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key azureuser@20.2.89.174 << 'EOF'

            source ~/.nvm/nvm.sh
            cd ~/100xdevs_w-45

            git pull origin production

            pnpm install

            cd packages/prisma
            npx prisma generate --config prisma.config.ts

            cd ~/100xdevs_w-45

            pnpm run build

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server

          EOF